## Reiniciando variáveis <br>
Um aspecto importante da programação em Python é ter controle sobre as variáveis inicializadas. Por isso, é sempre importante reiniciar todas as variáveis sempre que um programa em Python for implementado. Para "limpar" as variáveis, usamos os comandos:

In [1]:
# Limpando as variáveis
from IPython import get_ipython
get_ipython().magic('reset -sf')

C:\Users\João Pedro Holanda\AppData\Local\Temp\ipykernel_7700\2420803527.py:3: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic('reset -sf')


Note que se chamarmos esses comandos após a inicialização, haverá uma mensagem de erro:

In [2]:
x = [1,2,3]
print("x = ", x)

# Limpando as variáveis
from IPython import get_ipython
get_ipython().magic('reset -sf')

print("x = ", x) # Note que um erro será mostrado, pois x foi reiniciado

x =  [1, 2, 3]


C:\Users\João Pedro Holanda\AppData\Local\Temp\ipykernel_7700\2493441159.py:6: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic('reset -sf')


NameError: name 'x' is not defined

## Tipos de dados <br>
A linguagem Python suporta diversos tipos de dados, como int, float e strings. Para variáveis do tipo inteiro:

In [3]:
a = 2
print(a)

2


Float:

In [4]:
a = 2.5
print(a)

2.5


Também podemos converter de float para inteiro:

In [5]:
a = int(3/2)
print(a)

1


Números complexos:

In [7]:
a = 1.5+0.5j
print(a)

(1.5+0.5j)


In [8]:
print('Parte real:', a.real, 'Parte imaginária:', a.imag)

Parte real: 1.5 Parte imaginária: 0.5


Tipos booleanos:

In [10]:
a = 3 > 4
print('a =', a)
b = True
print('b =', b)
c = False
print('c =', c)

a = False
b = True
c = False


Para determinar o tipo de uma variável:

In [11]:
a = 3.5
print('Tipo de a:', type(a))
b = False
print('Tipoe de b:', type(b))

Tipo de a: <class 'float'>
Tipoe de b: <class 'bool'>


Para somar duas variáveis escalares:

In [12]:
x = 1
y = 2
z = x + y
print("z =", z)

z = 3


Multiplicação e potenciação:

In [13]:
a = 2
b = 2.3
print("a*b =", a*b)
print("a^3 =", a**3)

a*b = 4.6
a^3 = 8


Para determinarmos o resto de uma divisão:

In [14]:
a = 5%2
print(a)

1


## Listas <br>
Uma lista é um conjunto de dados onde os elementos não precisam ser do mesmo tipo:

In [15]:
L = [1, 2, 'a', 'palavra', 1.5+0.5j]
print(L)

[1, 2, 'a', 'palavra', (1.5+0.5j)]


Para acessar um elemento da lista:

In [16]:
print(L[0], L[2])

1 a


Índices negativos são usados para acessar do final para o começo:

In [17]:
print(L[-1], L[-2], L[-3])

(1.5+0.5j) palavra a


Podemos acessar vários elementos de uma vez:

In [18]:
print(L[0:4])

[1, 2, 'a', 'palavra']


Para adicionar um novo elemento na lista:

In [19]:
L.append('Novo elemento')
print(L)

[1, 2, 'a', 'palavra', (1.5+0.5j), 'Novo elemento']


Para remover o último elemento:

In [20]:
L.pop()
print(L)

[1, 2, 'a', 'palavra', (1.5+0.5j)]


Para inverter a ordem dos elementos:

In [22]:
L = L[::-1]
print(L)

[(1.5+0.5j), 'palavra', 'a', 2, 1]


Para concatenar uma lista:

In [23]:
L = [1, 2, 'a', 'palavra', 2.5, 1.5+0.5j]
k = [0, 9, 3, 'mundo']
m = L + k
print(m)

[1, 2, 'a', 'palavra', 2.5, (1.5+0.5j), 0, 9, 3, 'mundo']


Para repetir os elementos uma lista:

In [24]:
L = [1, 2, 'a', 'palavra', 2.5, 1.5+0.5j]
k = 2*L
print(k)

[1, 2, 'a', 'palavra', 2.5, (1.5+0.5j), 1, 2, 'a', 'palavra', 2.5, (1.5+0.5j)]


Ordenando uma lista:

In [25]:
L = [4,3,1,5,6,8,9]
L.sort()
print(L)

[1, 3, 4, 5, 6, 8, 9]


Note que a soma dos elementos de listas não é feita de forma direta:

In [26]:
x = [1,2,3]
y = [4,5,6]
z = x + y
print('z =', z)

z = [1, 2, 3, 4, 5, 6]


Para somar os elementos de uma lista, podemos usar a biblioteca numpy:

In [27]:
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = np.add(x, y)
print('z =', z)

z = [5 7 9]


Outra maneira de realizar essa soma é converter as listas para vetores:

In [28]:
x = [1,2,3]
x = np.array(x)
y = [4,5,6]
y = np.array(y)
z = x + y
print('z =', z)

z = [5 7 9]


## Vetores e matrizes <br>
Vetores e matrizes não sao tipos de dados padrões da linguagem Python. Para trabalharmos com dados númericos, podemos usar a biblioteca Numpy, que é uma biblioteca científica para cálculo de vetores multidimensionais. <br>
Para definirmos dois vetores e realizarmos a soma:

In [1]:
import numpy as np # os comandos da biblioteca numpy serão precedido pelo np

x = np.array([1,5,2])
y = np.array([7,4,1])
z = x + y
print(z)

[8 9 3]


Para iniciar um vetor com elementos iguais a zero ou um, usamos os seguintes comandos:

In [2]:
import numpy as np
N = 3
x = np.zeros(N)
y = np.ones(N)
print("x =", x, "y =", y)

x = [0. 0. 0.] y = [1. 1. 1.]


Para sabermos o tamanho de um vetor, usamos o comando:

In [3]:
x = [1,2,3]
x = np.array(x)
N = np.shape(x)[0]
print("N =", N)

N = 3


O produto escalar de dois vetores:

In [4]:
x = np.array([1,2,3])
y = np.array([1,4,6])
z = np.dot(x,y)
print(z)

27


E o produto vetorial:

In [5]:
x = np.array([0,0,1])
y = np.array([0,1,0])
z = np.cross(x,y)
print(z)

[-1  0  0]


Além de vetores, podemos definir variáveis como matrizes. Uma maneira é considerar uma lista de listas:

In [6]:
A = [[1,3,3], [4,5,6], [7,8,9]]
print("A =", A)

A = [[1, 3, 3], [4, 5, 6], [7, 8, 9]]


Nesse caso, deve-se atentar para a operação "+", que não representa a soma dos elementos, mas uma união de listas.

In [7]:
A = [[1,2,3], [4,5,6], [7,8,9]]
B = [[-1,-2,-3], [1,1,1], [0,0,0]]
C = A + B
print("C = ", C)

C =  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [-1, -2, -3], [1, 1, 1], [0, 0, 0]]


Para usar matrizes de maneira usual, é mais adequado consideramos a biblioteca Numpy:

In [8]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[10,11,12], [13,14,15], [16,17,18]])
C = 2*(A + B)
print("A = \n", A)
print("B = \n", B)
print("C =2*(A + B) = \n", C)

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
C =2*(A + B) = 
 [[22 26 30]
 [34 38 42]
 [46 50 54]]


Para saber o número de linhas e colunas em uma matriz, usamos:

In [9]:
A = np.array([[1,2,3], [4,5,6]])
[nrow, ncol] = np.shape(A)
print("A = \n", A)
print("Numero de linhas:", nrow, "\nNumero de colunas:", ncol,)

A = 
 [[1 2 3]
 [4 5 6]]
Numero de linhas: 2 
Numero de colunas: 3


Para elevar os elementos de um vetor a uma data potência:

In [10]:
x = np.array([1,2,3])
y = x**3
print(y)

[ 1  8 27]


Também podemos usar a função pow():

In [11]:
n = 3
x = np.array([1,2,3])
y = pow(x,n)
print(y)

[ 1  8 27]


## Strings <br>
Para definirmos uma string:

In [12]:
s = 'Hello World'

Uma string é interpretada como uma lista de caracteres:

In [13]:
print(s[0:5])

Hello


Podemos realizar operações em strings:

In [14]:
s = 'Hello'
t = 'World'
v = s + t
print(v)
print(s + '\t' + t)

HelloWorld
Hello	World


In [15]:
s = 'A'
t = 4*s
print(t)

AAAA


Podemos procurar uma palavra dentro de uma frase com operador 'in':

In [16]:
s = 'Mundo'
s in 'Mundo, mundo vasto mundo.'

True

In [17]:
s in 'A Terra é um planeta azul.'

False

Para sabermos o tamanho de uma string:

In [18]:
s = 'Hello'
print(len(s))

5


Podemos ainda converter números para string com a função 'str':

In [19]:
x = 2
s = 'O número ' + str(x) + ' é par'
print(s)

O número 2 é par


In [20]:
s = 'Pi é igual a ' + str(np.pi)
print(s)

Pi é igual a 3.141592653589793


Podemos acessar apenas alguns dos elementos da string:

In [21]:
s = 'ABCDEFGHIJK'
print(s[0:8:2]) # começando na posição 0 e selecionando de 2 em 2.

ACEG


Mostrando o valor de uma string (notem o caracter 'f' dentro da função print):

In [22]:
n = 20
m = 25
prod = n*m
print(f'O produto de {n} e {m} is {prod}')

O produto de 20 e 25 is 500


Podemos substituir um valor em uma string usando o comando replace:

In [24]:
s = 'Hello world'
x = 'Earth'
s = s.replace('world', x)
print(s)

Hello Earth


Mudando para letras minúsculas ou maíusculas:

In [25]:
'HELLo worlD'.lower()

'hello world'

In [26]:
s = 'Hello world'
s.upper()

'HELLO WORLD'

Outros comandos úteis:

In [27]:
'este eh um teste'.count('te')

3

In [28]:
'comando'.endswith('do')

True

In [29]:
'esta eh uma sentenca'.find('uma')

8

In [30]:
'esta eh uma sentenca'.find('nada')

-1

In [31]:
'O mundo é pequeno.'.replace('pequeno', 'grande')

'O mundo é grande.'

In [32]:
l = list('world')
print(l)
':'.join('world')

['w', 'o', 'r', 'l', 'd']


'w:o:r:l:d'

In [33]:
'esta eh uma sentenca'.rsplit()

['esta', 'eh', 'uma', 'sentenca']

In [34]:
'www.amazon.com.br'.rsplit(sep='.', maxsplit=3)

['www', 'amazon', 'com', 'br']

## Dicionários <br>
Dicionários são similires a listas, mas podem usar qualquer tipo imutável de dados como índice.

In [1]:
tel = {'Antonio': 5752, 'Maria': 5578}
tel['Paulo'] = 5915
print(tel)
print(tel['Antonio'])

{'Antonio': 5752, 'Maria': 5578, 'Paulo': 5915}
5752


Para acessar as chaves:

In [2]:
tel.keys()

dict_keys(['Antonio', 'Maria', 'Paulo'])

E os valores armazenados:

In [3]:
tel.values()

dict_values([5752, 5578, 5915])

Dicionários podem armazenar tipos diferentes:

In [4]:
d = {'a':1, 'b':2, 3:'hello'}
print(d)

{'a': 1, 'b': 2, 3: 'hello'}


Podemos realizar operações com dicionários:

In [5]:
estoque = {'abacaxis': 10, 'bananas': 24, 'laranjas': 36, 'peras': 12}
del estoque['peras']
print(estoque)

{'abacaxis': 10, 'bananas': 24, 'laranjas': 36}


In [6]:
estoque['abacaxis'] = estoque['abacaxis'] + 10
print(estoque)

{'abacaxis': 20, 'bananas': 24, 'laranjas': 36}


Dicionários podem ser usados para criar histogramas:

In [7]:
letterCounts = {}
for letter in "banana":
  letterCounts[letter] = letterCounts.get(letter,0) + 1
print(letterCounts)

{'b': 1, 'a': 3, 'n': 2}


## Estruturas Condicionais <br>
O comando if tem a seguinte estrutura: <br>
if condition: <br>
  if_body <br>
else: <br>
  else_body <br>
Note que após a condição, usamos ':' e a linha a seguir deve conter um espaço antes do comando. Por exemplo, para verificarmos se um número é par:

In [8]:
x = 3
if x%2 == 0: # O comando % retorna o resto da divisão
  print('x é par.')
else:
  print('x é ímpar.')

x é ímpar.


Além do comando if, podemos usar o comando elif, para combinar condicionais:

In [10]:
a = 200
b = 33
if b > a:
  print('b é maior do que a.')
elif a == b:
  print('a e b são iguais.')
else:
  print('a é maior do que b.')

a é maior do que b.


Para executar o comando em uma única linha:

In [11]:
if a > b: print('a é maior do que b')

a é maior do que b


Ou então:

In [12]:
a = 3
b = 4
print("A") if a > b else print("=") if a == b else print("B")

B
