Um dos primeiros passos em Ciência de Dados é a preparação e transformação dos dados, de modo a prepará-los para etapas posteriores. <br>
Nessa aula, vamos considerar dados com elementos duplicados ou faltantes e realizar sua limpeza. Também vamos considerar métodos básiscos de pré-processamento e transformação de dados. <br>
Vamos ler um conjunto de dados com erros:

In [1]:
#gerador de números aleatórios
import random
random.seed(1) #inicia a semente do gerador de números aleatórios. 
import pandas as pd #biblioteca pandas é usada para manipulação de dados
import matplotlib.pyplot as plt #biblioteca para visualização dos dados

#csv file
data = pd.read_csv('iris-with-errors.csv', header=(0))
print("Número de linhas e colunas:", data.shape)
data.head(25)

Número de linhas e colunas: (25, 5)


sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
2             ?           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
5           NaN         3.1           1.5         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
9           4.6         3.4           1.4         NaN     setosa
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3           ?     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7           ?           1.7         0.3     setosa
24          NaN         3.8           1.5         0.3     setosa

Primeiramente, vamos remover os "NaN" (not a number, que representam valores desconhecidos) do arquivo, apagando as linhas que contém esse problema. Notem que algumas linhas serão removidas, tais como a 5 e 9.

In [2]:
#remove as linhas com NaN
data = data.dropna()
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
2             ?           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3           ?     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7           ?           1.7         0.3     setosa

Vamos remover as linhas duplicadas. Para isso, inicialmente verificamos se há a ocorrência dessas linhas.

In [3]:
#Retorna True na posição em que há uma linha duplicada
data.duplicated()

0     False
1      True
2     False
3     False
4      True
6     False
7     False
8      True
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
dtype: bool

Notem que indicamos nos dados originais, na última coluna, quais linhas estão duplicadas. <br>
Para realizarmos a remoção, usamos um método da biblioteca Pandas.

In [4]:
#Remove as linhas duplicadas
data = data.drop_duplicates()
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
2             ?           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3           ?     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7           ?           1.7         0.3     setosa

Compara essa tabela com a original (acima) e verifique se a remoção das linhas foi feita de forma correta. As linhas duplicadas são indicadas na última coluna. <br>
Vamos remover as linhas que contenham "?" ou qualquer outro caracter que indique um erro ou entrada faltante. <br>
Primeiramente, convertemos essas entradas para "NaN":

In [5]:
import numpy as np
#Substitui NaN por um caracter desejado
data = data.replace('?', np.nan)
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
2           NaN           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3         NaN     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7         NaN           1.7         0.3     setosa

A seguir, fazemos a remoção, como anteriormente.

In [6]:
#Remove as linhas com NaN
data = data.dropna()
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
3           4.7         3.2           1.3         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
22          5.1         3.5           1.4         0.3     setosa

Dessa forma, temos um conjunto de dados sem erros e entradas duplicadas. É fundamental realizar essas operações em qualquer conjunto de dados antes de aplicarmos os métodos de aprendizado de máquina e estatística. <br>
Podemos também remover determinadas linhas e colunas dos dados. Para remover a segunda e quarta colunas:

In [7]:
print("Atributos atuais:", data.columns)
print("Colunas removidas:", data.columns[[1, 3]])
#Remove as linhas especificadas
data = data.drop(data.columns[[1, 3]], axis=1)
data.head(25)

Atributos atuais: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
Colunas removidas: Index(['sepal_width', 'petal_width'], dtype='object')


sepal_length  petal_length    species
0           5.1           1.4  duplicada
3           4.7           1.3     setosa
6             5           1.4     setosa
7           5.4           1.7  duplicada
10            5           1.5     setosa
11          4.4           1.4  duplicada
12          4.9           1.5     setosa
13          5.4           1.5     setosa
15          4.8           1.6     setosa
16          4.8           1.4     setosa
18          4.3           1.1     setosa
19          5.8           1.2     setosa
20          5.7           1.5     setosa
22          5.1           1.4     setosa

Para remover a primeira e terceira linhas:

In [8]:
data = data.drop(data.index[[0, 2]], axis=0)
print("Linhas Removidas:", data.index[[0, 2]])
data.head(25)

Linhas Removidas: Int64Index([3, 10], dtype='int64')


sepal_length  petal_length    species
3           4.7           1.3     setosa
7           5.4           1.7  duplicada
10            5           1.5     setosa
11          4.4           1.4  duplicada
12          4.9           1.5     setosa
13          5.4           1.5     setosa
15          4.8           1.6     setosa
16          4.8           1.4     setosa
18          4.3           1.1     setosa
19          5.8           1.2     setosa
20          5.7           1.5     setosa
22          5.1           1.4     setosa

### Substituição de valores ausentes <br>
Em muitas situações, a matriz de atributos pode conter valores ausentes. Nesse caso, podemos usar diferentes métodos para substituir tais valores, como preenche-lhos com valores médios ou medianas. <br>
Vamos ler os dados novamente:

In [9]:
data = pd.read_csv('iris-with-errors.csv', header=(0))
print(data.shape)
data.head(25)

(25, 5)


sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
2             ?           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
5           NaN         3.1           1.5         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
9           4.6         3.4           1.4         NaN     setosa
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3           ?     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7           ?           1.7         0.3     setosa
24          NaN         3.8           1.5         0.3     setosa

Vamos substituir os valores com "NaN" e "?" pelos valores médios dos atributos. Primeiramente, mudamos as entradas "?" para "NaN", como foi feito anteriormente.

In [10]:
import numpy as np
data = data.replace('?', np.nan)
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
2           NaN           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
5           NaN         3.1           1.5         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
9           4.6         3.4           1.4         NaN     setosa
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3         NaN     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7         NaN           1.7         0.3     setosa
24          NaN         3.8           1.5         0.3     setosa

A seguir, inserirmos a média de cada atributo nas entradas com valores "NaN".

In [11]:
#convertemos para o formato Numpy e ignoramos a última coluna (classe)
X = np.array(data[data.columns[0:data.shape[1]-1]], dtype=float)
#calculamos a média de cada atributo e armazenamos em um vetor
#usamos a função nanmean que calcula a média ignorando os NaN
averages = np.nanmean(X, axis=0) 
for i in np.arange(0, X.shape[0]):
  for j in np.arange(0, X.shape[1]):
    if(np.isnan(X[i,j]) == True): #verificar se é uma entrada com NaN
      X[i,j] = averages[j] #insere a média
print(X)

[[5.1        3.5        1.4        0.2       ]
 [5.1        3.5        1.4        0.2       ]
 [5.02272727 3.         1.4        0.2       ]
 [4.7        3.2        1.3        0.2       ]
 [5.1        3.5        1.4        0.2       ]
 [5.02272727 3.1        1.5        0.2       ]
 [5.         3.6        1.4        0.2       ]
 [5.4        3.9        1.7        0.4       ]
 [5.4        3.9        1.7        0.4       ]
 [4.6        3.4        1.4        0.22608696]
 [5.         3.4        1.5        0.2       ]
 [4.4        2.9        1.4        0.2       ]
 [4.9        3.1        1.5        0.1       ]
 [5.4        3.7        1.5        0.2       ]
 [4.4        2.9        1.4        0.2       ]
 [4.8        3.4        1.6        0.2       ]
 [4.8        3.         1.4        0.1       ]
 [4.4        2.9        1.4        0.2       ]
 [4.3        3.         1.1        0.1       ]
 [5.8        4.         1.2        0.2       ]
 [5.7        4.4        1.5        0.4       ]
 [5.4        

Assim como inserimos a média, poderíamos inserir a mediana ou qualquer outro valor.

### Normalização e padronização <br>
Vamos ler os dados:

In [12]:
import pandas as pd
#csv file
data = pd.read_csv('iris.csv', header=(0))
print(data.shape)
data.head(25)

(150, 5)


sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa

Para normalzar os dados no intervalo [0,1]:

In [13]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
#considera somente os atributos, ignorando a última coluna, que contém a classe
X = np.array(data[data.columns[0:data.shape[1]-1]])
for i in range(X.shape[1]):
  print("Maior valor da coluna:", i, ":", max(X[:,i]))
  print("Menor valor da coluna:", i, ":", min(X[:,i]))
#prepara a função para transformar os dados
scaler = MinMaxScaler(feature_range=(0,1))
#realiza a normalização e coloca em um novo vetor
X_norm = scaler.fit_transform(X)
print(X_norm)

Maior valor da coluna: 0 : 7.9
Menor valor da coluna: 0 : 4.3
Maior valor da coluna: 1 : 4.4
Menor valor da coluna: 1 : 2.0
Maior valor da coluna: 2 : 6.9
Menor valor da coluna: 2 : 1.0
Maior valor da coluna: 3 : 2.5
Menor valor da coluna: 3 : 0.1
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]


Ou seja, o máximo e mínimo do novo conjunto de dados:

In [14]:
print("Mínimo dos atributos:", np.amin(X_norm, axis=0))
print("Máximo dos atributos:", np.amin(X_norm, axis=0))

Mínimo dos atributos: [0. 0. 0. 0.]
Máximo dos atributos: [0. 0. 0. 0.]


Para realizarmos a padronização dos dados, de forma que os atributos apresentem média igual a zero e variância igual a 1, o procedimento é parecido

In [15]:
from sklearn.preprocessing import StandardScaler
X = np.array(data[data.columns[0:data.shape[1]-1]])
#prepara a função para transformar os dados
scaler = StandardScaler().fit(X)
#realiza a padronização (média=0, variância=1)
rescaledX = scaler.transform(X)
print(rescaledX)


[[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.06445364e-01 -1.28440670e+00 -1.44444970e+00]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [-1.26418478e+00  8.00654259e-01 -1.22754100e+00 -1.31297673e+00]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.87002413e+00 -1.24957601e-01 -1.51186952e+00 -1.44444970e+00]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e

Vamos verificar se cada coluna apresenta média igual a zero e desvio padrão igual a um.

In [16]:
for i in np.arange(0, rescaledX.shape[1]):
  print("Média da coluna", i, 'é igual a:', np.mean(rescaledX[:,i]))
  print("Desvio padrão da coluna", i, 'é igual a:', np.std(rescaledX[:,i]), '\n')

Média da coluna 0 é igual a: -4.736951571734001e-16
Desvio padrão da coluna 0 é igual a: 1.0 

Média da coluna 1 é igual a: -6.631732200427602e-16
Desvio padrão da coluna 1 é igual a: 0.9999999999999999 

Média da coluna 2 é igual a: 3.315866100213801e-16
Desvio padrão da coluna 2 é igual a: 0.9999999999999998 

Média da coluna 3 é igual a: -2.842170943040401e-16
Desvio padrão da coluna 3 é igual a: 1.0 



### Binarização dos dados <br>
A binarização dos dados resulta em valores zero ou um, de acordo com um dado limiar. Ou seja, se o valor em X for maior do que o limiar, o valor resultante será um, caso contrário será zero.

In [17]:
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import MinMaxScaler

#considera apenas os atributos, ignorando a última coluna das classes
X = np.array(data[data.columns[0:data.shape[1]-1]], dtype=float)
T = 0.2 #valor do limiar
print('Limiar:', T)
print('-----')

#prepara a normalização dos dados
scaler = MinMaxScaler(feature_range=(0,1))
#realiza a normalização
X_pad = scaler.fit_transform(X)
#faz a binarização considerando o limiar (threshold)
binarizer = Binarizer(threshold=T).fit(X_pad)
binaryX = binarizer.transform(X_pad)
for i in np.arange(0, X_pad.shape[0]):
  print("Antes:", X_pad[i,])
  print("Depois:", binaryX[i,])
  print('-----')

Limiar: 0.2
-----
Antes: [0.22222222 0.625      0.06779661 0.04166667]
Depois: [1. 1. 0. 0.]
-----
Antes: [0.16666667 0.41666667 0.06779661 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.11111111 0.5        0.05084746 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.08333333 0.45833333 0.08474576 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.19444444 0.66666667 0.06779661 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.30555556 0.79166667 0.11864407 0.125     ]
Depois: [1. 1. 0. 0.]
-----
Antes: [0.08333333 0.58333333 0.06779661 0.08333333]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.19444444 0.58333333 0.08474576 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.02777778 0.375      0.06779661 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.16666667 0.45833333 0.08474576 0.        ]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.30555556 0.70833333 0.08474576 0.04166667]
Depois: [1. 1. 0. 0.]
-----
Antes: [0.13888889 0.58333333 0.10169492 0.04166667]
Depois: [0. 1. 0. 0.]
-----
Antes: [0.

### Conversão de variáveis nominais em inteiros <br>
Quando temos dados nominais e ordinais, podemos convertê-los para variáveis numéricas. Vamos fazer isso com as classes dos dados, mudando os valores nominais para inteiros.

In [18]:
#leitura dos dados
data = pd.read_csv('iris.csv', header=(0))
print('Número de linhas e colunas:', data.shape)
#mostramos a última coluna
print('Coluna com as classes:\n', data[data.columns[-1]])

Número de linhas e colunas: (150, 5)
Coluna com as classes:
 0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [19]:
#armazena o nome das classes
classes = np.unique(data[data.columns[-1]])
number = 0 #valor que será usado para representar as classes
for i in classes:
  data = data.replace(i, number) #substitui cada valor da classe por número
  number += 1
print('Novos dados:')
print(data[data.columns[-1]])

Novos dados:
0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64


Esse mesmo procedimento pode ser usado em qualquer uma das colunas da matriz de atributos.

### One-hot encoding <br>
Quando temos variáveis nominais e precisamos transformá-las para numéricas, uma maneira simples é usar o método one-hot enconding.

In [20]:
import pandas as pd

#cria um dataframe do Pandas
df = pd.DataFrame({
  'A':['a', 'b', 'a', 'c', 'a', 'b'],
  })
df.head()

A
0  a
1  b
2  a
3  c
4  a

Usando one-hot enconding, obtemos:

In [21]:
df = pd.get_dummies(df)
df.head()

A_a  A_b  A_c
0    1    0    0
1    0    1    0
2    1    0    0
3    0    0    1
4    1    0    0

Note que foi usado em código binário para cada valor nominal.